// Mocks generated by Mockito 5.4.6 from annotations
// in giving_bridge_frontend/test/provider_tests.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:giving_bridge_frontend/models/donation.dart' as _i7;
import 'package:giving_bridge_frontend/repositories/base_repository.dart'
    as _i2;
import 'package:giving_bridge_frontend/repositories/donation_repository.dart'
    as _i4;
import 'package:giving_bridge_frontend/repositories/message_repository.dart'
    as _i9;
import 'package:giving_bridge_frontend/repositories/request_repository.dart'
    as _i8;
import 'package:http/http.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1 extends _i1.SmartFake implements _i3.Response {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DonationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDonationRepository extends _i1.Mock
    implements _i4.DonationRepository {
  MockDonationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i6.Future<_i2.ApiResponse<List<_i7.Donation>>> getDonations({
    String? category,
    String? location,
    bool? available,
    int? page = 1,
    int? limit = 20,
    String? sort,
    String? order,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDonations,
          [],
          {
            #category: category,
            #location: location,
            #available: available,
            #page: page,
            #limit: limit,
            #sort: sort,
            #order: order,
          },
        ),
        returnValue: _i6.Future<_i2.ApiResponse<List<_i7.Donation>>>.value(
            _FakeApiResponse_0<List<_i7.Donation>>(
          this,
          Invocation.method(
            #getDonations,
            [],
            {
              #category: category,
              #location: location,
              #available: available,
              #page: page,
              #limit: limit,
              #sort: sort,
              #order: order,
            },
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<List<_i7.Donation>>>);

  @override
  _i6.Future<_i2.ApiResponse<_i7.Donation>> getDonation(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDonation,
          [id],
        ),
        returnValue: _i6.Future<_i2.ApiResponse<_i7.Donation>>.value(
            _FakeApiResponse_0<_i7.Donation>(
          this,
          Invocation.method(
            #getDonation,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<_i7.Donation>>);

  @override
  _i6.Future<_i2.ApiResponse<List<_i7.Donation>>> getMyDonations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyDonations,
          [],
        ),
        returnValue: _i6.Future<_i2.ApiResponse<List<_i7.Donation>>>.value(
            _FakeApiResponse_0<List<_i7.Donation>>(
          this,
          Invocation.method(
            #getMyDonations,
            [],
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<List<_i7.Donation>>>);

  @override
  _i6.Future<_i2.ApiResponse<_i7.Donation>> createDonation({
    required String? title,
    required String? description,
    required String? category,
    required String? condition,
    required String? location,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDonation,
          [],
          {
            #title: title,
            #description: description,
            #category: category,
            #condition: condition,
            #location: location,
            #imageUrl: imageUrl,
          },
        ),
        returnValue: _i6.Future<_i2.ApiResponse<_i7.Donation>>.value(
            _FakeApiResponse_0<_i7.Donation>(
          this,
          Invocation.method(
            #createDonation,
            [],
            {
              #title: title,
              #description: description,
              #category: category,
              #condition: condition,
              #location: location,
              #imageUrl: imageUrl,
            },
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<_i7.Donation>>);

  @override
  _i6.Future<_i2.ApiResponse<_i7.Donation>> updateDonation({
    required String? id,
    String? title,
    String? description,
    String? category,
    String? condition,
    String? location,
    String? imageUrl,
    bool? isAvailable,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDonation,
          [],
          {
            #id: id,
            #title: title,
            #description: description,
            #category: category,
            #condition: condition,
            #location: location,
            #imageUrl: imageUrl,
            #isAvailable: isAvailable,
          },
        ),
        returnValue: _i6.Future<_i2.ApiResponse<_i7.Donation>>.value(
            _FakeApiResponse_0<_i7.Donation>(
          this,
          Invocation.method(
            #updateDonation,
            [],
            {
              #id: id,
              #title: title,
              #description: description,
              #category: category,
              #condition: condition,
              #location: location,
              #imageUrl: imageUrl,
              #isAvailable: isAvailable,
            },
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<_i7.Donation>>);

  @override
  _i6.Future<_i2.ApiResponse<String>> deleteDonation(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDonation,
          [id],
        ),
        returnValue: _i6.Future<_i2.ApiResponse<String>>.value(
            _FakeApiResponse_0<String>(
          this,
          Invocation.method(
            #deleteDonation,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<String>>);

  @override
  _i6.Future<_i2.ApiResponse<Map<String, dynamic>>> getDonationStats() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDonationStats,
          [],
        ),
        returnValue: _i6.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
            _FakeApiResponse_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getDonationStats,
            [],
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  _i6.Future<_i2.ApiResponse<List<_i7.Donation>>> searchDonations({
    required String? query,
    String? category,
    String? location,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchDonations,
          [],
          {
            #query: query,
            #category: category,
            #location: location,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i6.Future<_i2.ApiResponse<List<_i7.Donation>>>.value(
            _FakeApiResponse_0<List<_i7.Donation>>(
          this,
          Invocation.method(
            #searchDonations,
            [],
            {
              #query: query,
              #category: category,
              #location: location,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<List<_i7.Donation>>>);

  @override
  _i6.Future<_i3.Response> get(
    String? endpoint, {
    bool? includeAuth = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {#includeAuth: includeAuth},
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {#includeAuth: includeAuth},
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<_i3.Response> post(
    String? endpoint,
    Map<String, dynamic>? body, {
    bool? includeAuth = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [
            endpoint,
            body,
          ],
          {#includeAuth: includeAuth},
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #post,
            [
              endpoint,
              body,
            ],
            {#includeAuth: includeAuth},
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<_i3.Response> put(
    String? endpoint,
    Map<String, dynamic>? body, {
    bool? includeAuth = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            endpoint,
            body,
          ],
          {#includeAuth: includeAuth},
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #put,
            [
              endpoint,
              body,
            ],
            {#includeAuth: includeAuth},
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<_i3.Response> delete(
    String? endpoint, {
    bool? includeAuth = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
          {#includeAuth: includeAuth},
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #delete,
            [endpoint],
            {#includeAuth: includeAuth},
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i2.ApiResponse<T> handleResponse<T>(
    _i3.Response? response,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleResponse,
          [
            response,
            fromJson,
          ],
        ),
        returnValue: _FakeApiResponse_0<T>(
          this,
          Invocation.method(
            #handleResponse,
            [
              response,
              fromJson,
            ],
          ),
        ),
      ) as _i2.ApiResponse<T>);

  @override
  _i2.ApiResponse<List<T>> handleListResponse<T>(
    _i3.Response? response,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleListResponse,
          [
            response,
            fromJson,
          ],
        ),
        returnValue: _FakeApiResponse_0<List<T>>(
          this,
          Invocation.method(
            #handleListResponse,
            [
              response,
              fromJson,
            ],
          ),
        ),
      ) as _i2.ApiResponse<List<T>>);
}

/// A class which mocks [RequestRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestRepository extends _i1.Mock implements _i8.RequestRepository {
  MockRequestRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i6.Future<_i2.ApiResponse<List<dynamic>>> getRequests({
    String? donationId,
    String? status,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRequests,
          [],
          {
            #donationId: donationId,
            #status: status,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i6.Future<_i2.ApiResponse<List<dynamic>>>.value(
            _FakeApiResponse_0<List<dynamic>>(
          this,
          Invocation.method(
            #getRequests,
            [],
            {
              #donationId: donationId,
              #status: status,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<List<dynamic>>>);

  @override
  _i6.Future<_i2.ApiResponse<List<dynamic>>> getMyRequests({
    String? status,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyRequests,
          [],
          {
            #status: status,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i6.Future<_i2.ApiResponse<List<dynamic>>>.value(
            _FakeApiResponse_0<List<dynamic>>(
          this,
          Invocation.method(
            #getMyRequests,
            [],
            {
              #status: status,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<List<dynamic>>>);

  @override
  _i6.Future<_i2.ApiResponse<List<dynamic>>> getIncomingRequests({
    String? status,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIncomingRequests,
          [],
          {
            #status: status,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i6.Future<_i2.ApiResponse<List<dynamic>>>.value(
            _FakeApiResponse_0<List<dynamic>>(
          this,
          Invocation.method(
            #getIncomingRequests,
            [],
            {
              #status: status,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<List<dynamic>>>);

  @override
  _i6.Future<_i2.ApiResponse<dynamic>> createRequest({
    required String? donationId,
    String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRequest,
          [],
          {
            #donationId: donationId,
            #message: message,
          },
        ),
        returnValue: _i6.Future<_i2.ApiResponse<dynamic>>.value(
            _FakeApiResponse_0<dynamic>(
          this,
          Invocation.method(
            #createRequest,
            [],
            {
              #donationId: donationId,
              #message: message,
            },
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<dynamic>>);

  @override
  _i6.Future<_i2.ApiResponse<dynamic>> updateRequestStatus({
    required String? requestId,
    required String? status,
    String? responseMessage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRequestStatus,
          [],
          {
            #requestId: requestId,
            #status: status,
            #responseMessage: responseMessage,
          },
        ),
        returnValue: _i6.Future<_i2.ApiResponse<dynamic>>.value(
            _FakeApiResponse_0<dynamic>(
          this,
          Invocation.method(
            #updateRequestStatus,
            [],
            {
              #requestId: requestId,
              #status: status,
              #responseMessage: responseMessage,
            },
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<dynamic>>);

  @override
  _i6.Future<_i2.ApiResponse<String>> deleteRequest(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRequest,
          [id],
        ),
        returnValue: _i6.Future<_i2.ApiResponse<String>>.value(
            _FakeApiResponse_0<String>(
          this,
          Invocation.method(
            #deleteRequest,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<String>>);

  @override
  _i6.Future<_i2.ApiResponse<dynamic>> getRequestById(String? requestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRequestById,
          [requestId],
        ),
        returnValue: _i6.Future<_i2.ApiResponse<dynamic>>.value(
            _FakeApiResponse_0<dynamic>(
          this,
          Invocation.method(
            #getRequestById,
            [requestId],
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<dynamic>>);

  @override
  _i6.Future<_i2.ApiResponse<Map<String, dynamic>>> getRequestStats() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRequestStats,
          [],
        ),
        returnValue: _i6.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
            _FakeApiResponse_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getRequestStats,
            [],
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  _i6.Future<_i2.ApiResponse<List<dynamic>>> searchRequests({
    required String? query,
    String? status,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRequests,
          [],
          {
            #query: query,
            #status: status,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i6.Future<_i2.ApiResponse<List<dynamic>>>.value(
            _FakeApiResponse_0<List<dynamic>>(
          this,
          Invocation.method(
            #searchRequests,
            [],
            {
              #query: query,
              #status: status,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<List<dynamic>>>);

  @override
  _i6.Future<_i3.Response> get(
    String? endpoint, {
    bool? includeAuth = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {#includeAuth: includeAuth},
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {#includeAuth: includeAuth},
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<_i3.Response> post(
    String? endpoint,
    Map<String, dynamic>? body, {
    bool? includeAuth = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [
            endpoint,
            body,
          ],
          {#includeAuth: includeAuth},
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #post,
            [
              endpoint,
              body,
            ],
            {#includeAuth: includeAuth},
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<_i3.Response> put(
    String? endpoint,
    Map<String, dynamic>? body, {
    bool? includeAuth = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            endpoint,
            body,
          ],
          {#includeAuth: includeAuth},
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #put,
            [
              endpoint,
              body,
            ],
            {#includeAuth: includeAuth},
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<_i3.Response> delete(
    String? endpoint, {
    bool? includeAuth = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
          {#includeAuth: includeAuth},
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #delete,
            [endpoint],
            {#includeAuth: includeAuth},
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i2.ApiResponse<T> handleResponse<T>(
    _i3.Response? response,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleResponse,
          [
            response,
            fromJson,
          ],
        ),
        returnValue: _FakeApiResponse_0<T>(
          this,
          Invocation.method(
            #handleResponse,
            [
              response,
              fromJson,
            ],
          ),
        ),
      ) as _i2.ApiResponse<T>);

  @override
  _i2.ApiResponse<List<T>> handleListResponse<T>(
    _i3.Response? response,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleListResponse,
          [
            response,
            fromJson,
          ],
        ),
        returnValue: _FakeApiResponse_0<List<T>>(
          this,
          Invocation.method(
            #handleListResponse,
            [
              response,
              fromJson,
            ],
          ),
        ),
      ) as _i2.ApiResponse<List<T>>);
}

/// A class which mocks [MessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepository extends _i1.Mock implements _i9.MessageRepository {
  MockMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i6.Future<_i2.ApiResponse<List<dynamic>>> getConversations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversations,
          [],
        ),
        returnValue: _i6.Future<_i2.ApiResponse<List<dynamic>>>.value(
            _FakeApiResponse_0<List<dynamic>>(
          this,
          Invocation.method(
            #getConversations,
            [],
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<List<dynamic>>>);

  @override
  _i6.Future<_i2.ApiResponse<List<dynamic>>> getMessages({
    required String? userId,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [],
          {
            #userId: userId,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i6.Future<_i2.ApiResponse<List<dynamic>>>.value(
            _FakeApiResponse_0<List<dynamic>>(
          this,
          Invocation.method(
            #getMessages,
            [],
            {
              #userId: userId,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<List<dynamic>>>);

  @override
  _i6.Future<_i2.ApiResponse<dynamic>> sendMessage({
    required String receiverId,
    required String content,
    String? donationId,
    String? requestId,
    String? messageType,
    String? attachmentUrl,
    String? attachmentName,
    int? attachmentSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {
            #receiverId: receiverId,
            #content: content,
            #donationId: donationId,
            #requestId: requestId,
            #messageType: messageType,
            #attachmentUrl: attachmentUrl,
            #attachmentName: attachmentName,
            #attachmentSize: attachmentSize,
          },
        ),
        returnValue: _i6.Future<_i2.ApiResponse<dynamic>>.value(
            _FakeApiResponse_0<dynamic>(
          this,
          Invocation.method(
            #sendMessage,
            [],
            {
              #receiverId: receiverId,
              #content: content,
              #donationId: donationId,
              #requestId: requestId,
              #messageType: messageType,
              #attachmentUrl: attachmentUrl,
              #attachmentName: attachmentName,
              #attachmentSize: attachmentSize,
            },
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<dynamic>>);

  @override
  _i6.Future<_i2.ApiResponse<String>> markMessageAsRead(String? messageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMessageAsRead,
          [messageId],
        ),
        returnValue: _i6.Future<_i2.ApiResponse<String>>.value(
            _FakeApiResponse_0<String>(
          this,
          Invocation.method(
            #markMessageAsRead,
            [messageId],
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<String>>);

  @override
  _i6.Future<_i2.ApiResponse<String>> markConversationAsRead(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markConversationAsRead,
          [userId],
        ),
        returnValue: _i6.Future<_i2.ApiResponse<String>>.value(
            _FakeApiResponse_0<String>(
          this,
          Invocation.method(
            #markConversationAsRead,
            [userId],
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<String>>);

  @override
  _i6.Future<_i2.ApiResponse<int>> getUnreadMessageCount() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnreadMessageCount,
          [],
        ),
        returnValue:
            _i6.Future<_i2.ApiResponse<int>>.value(_FakeApiResponse_0<int>(
          this,
          Invocation.method(
            #getUnreadMessageCount,
            [],
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<int>>);

  @override
  _i6.Future<_i2.ApiResponse<String>> deleteMessage(String? messageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMessage,
          [messageId],
        ),
        returnValue: _i6.Future<_i2.ApiResponse<String>>.value(
            _FakeApiResponse_0<String>(
          this,
          Invocation.method(
            #deleteMessage,
            [messageId],
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<String>>);

  @override
  _i6.Future<_i2.ApiResponse<dynamic>> getMessageById(String? messageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessageById,
          [messageId],
        ),
        returnValue: _i6.Future<_i2.ApiResponse<dynamic>>.value(
            _FakeApiResponse_0<dynamic>(
          this,
          Invocation.method(
            #getMessageById,
            [messageId],
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<dynamic>>);

  @override
  _i6.Future<_i2.ApiResponse<List<dynamic>>> searchMessages({
    required String? query,
    String? userId,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMessages,
          [],
          {
            #query: query,
            #userId: userId,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i6.Future<_i2.ApiResponse<List<dynamic>>>.value(
            _FakeApiResponse_0<List<dynamic>>(
          this,
          Invocation.method(
            #searchMessages,
            [],
            {
              #query: query,
              #userId: userId,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i6.Future<_i2.ApiResponse<List<dynamic>>>);

  @override
  _i6.Future<_i3.Response> get(
    String? endpoint, {
    bool? includeAuth = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {#includeAuth: includeAuth},
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {#includeAuth: includeAuth},
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<_i3.Response> post(
    String? endpoint,
    Map<String, dynamic>? body, {
    bool? includeAuth = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [
            endpoint,
            body,
          ],
          {#includeAuth: includeAuth},
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #post,
            [
              endpoint,
              body,
            ],
            {#includeAuth: includeAuth},
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<_i3.Response> put(
    String? endpoint,
    Map<String, dynamic>? body, {
    bool? includeAuth = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            endpoint,
            body,
          ],
          {#includeAuth: includeAuth},
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #put,
            [
              endpoint,
              body,
            ],
            {#includeAuth: includeAuth},
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<_i3.Response> delete(
    String? endpoint, {
    bool? includeAuth = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
          {#includeAuth: includeAuth},
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #delete,
            [endpoint],
            {#includeAuth: includeAuth},
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i2.ApiResponse<T> handleResponse<T>(
    _i3.Response? response,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleResponse,
          [
            response,
            fromJson,
          ],
        ),
        returnValue: _FakeApiResponse_0<T>(
          this,
          Invocation.method(
            #handleResponse,
            [
              response,
              fromJson,
            ],
          ),
        ),
      ) as _i2.ApiResponse<T>);

  @override
  _i2.ApiResponse<List<T>> handleListResponse<T>(
    _i3.Response? response,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleListResponse,
          [
            response,
            fromJson,
          ],
        ),
        returnValue: _FakeApiResponse_0<List<T>>(
          this,
          Invocation.method(
            #handleListResponse,
            [
              response,
              fromJson,
            ],
          ),
        ),
      ) as _i2.ApiResponse<List<T>>);
}
