// Mocks generated by Mockito 5.4.6 from annotations
// in giving_bridge_frontend/test/widget_tests.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:giving_bridge_frontend/l10n/app_localizations.dart' as _i6;
import 'package:giving_bridge_frontend/models/donation.dart' as _i3;
import 'package:giving_bridge_frontend/providers/donation_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DonationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDonationProvider extends _i1.Mock implements _i2.DonationProvider {
  MockDonationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Donation> get donations => (super.noSuchMethod(
        Invocation.getter(#donations),
        returnValue: <_i3.Donation>[],
      ) as List<_i3.Donation>);

  @override
  List<_i3.Donation> get myDonations => (super.noSuchMethod(
        Invocation.getter(#myDonations),
        returnValue: <_i3.Donation>[],
      ) as List<_i3.Donation>);

  @override
  Map<String, dynamic> get stats => (super.noSuchMethod(
        Invocation.getter(#stats),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoadingMyDonations => (super.noSuchMethod(
        Invocation.getter(#isLoadingMyDonations),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoadingStats => (super.noSuchMethod(
        Invocation.getter(#isLoadingStats),
        returnValue: false,
      ) as bool);

  @override
  int get currentPage => (super.noSuchMethod(
        Invocation.getter(#currentPage),
        returnValue: 0,
      ) as int);

  @override
  bool get hasMoreData => (super.noSuchMethod(
        Invocation.getter(#hasMoreData),
        returnValue: false,
      ) as bool);

  @override
  List<_i3.Donation> get filteredDonations => (super.noSuchMethod(
        Invocation.getter(#filteredDonations),
        returnValue: <_i3.Donation>[],
      ) as List<_i3.Donation>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> loadDonations({bool? refresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadDonations,
          [],
          {#refresh: refresh},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadMoreDonations() => (super.noSuchMethod(
        Invocation.method(
          #loadMoreDonations,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadMyDonations() => (super.noSuchMethod(
        Invocation.method(
          #loadMyDonations,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadStats() => (super.noSuchMethod(
        Invocation.method(
          #loadStats,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> createDonation({
    required String? title,
    required String? description,
    required String? category,
    required String? condition,
    required String? location,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDonation,
          [],
          {
            #title: title,
            #description: description,
            #category: category,
            #condition: condition,
            #location: location,
            #imageUrl: imageUrl,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateDonation({
    required String? id,
    String? title,
    String? description,
    String? category,
    String? condition,
    String? location,
    String? imageUrl,
    bool? isAvailable,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDonation,
          [],
          {
            #id: id,
            #title: title,
            #description: description,
            #category: category,
            #condition: condition,
            #location: location,
            #imageUrl: imageUrl,
            #isAvailable: isAvailable,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteDonation(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteDonation,
          [id],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> searchDonations(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchDonations,
          [query],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void setCategoryFilter(String? category) => super.noSuchMethod(
        Invocation.method(
          #setCategoryFilter,
          [category],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLocationFilter(String? location) => super.noSuchMethod(
        Invocation.method(
          #setLocationFilter,
          [location],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAvailabilityFilter(bool? available) => super.noSuchMethod(
        Invocation.method(
          #setAvailabilityFilter,
          [available],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearFilters() => super.noSuchMethod(
        Invocation.method(
          #clearFilters,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i3.Donation? getDonationById(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getDonationById,
        [id],
      )) as _i3.Donation?);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AppLocalizations].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalizations extends _i1.Mock implements _i6.AppLocalizations {
  MockAppLocalizations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get localeName => (super.noSuchMethod(
        Invocation.getter(#localeName),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#localeName),
        ),
      ) as String);

  @override
  String get appTitle => (super.noSuchMethod(
        Invocation.getter(#appTitle),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#appTitle),
        ),
      ) as String);

  @override
  String get welcomeBack => (super.noSuchMethod(
        Invocation.getter(#welcomeBack),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#welcomeBack),
        ),
      ) as String);

  @override
  String get signIn => (super.noSuchMethod(
        Invocation.getter(#signIn),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#signIn),
        ),
      ) as String);

  @override
  String get signUp => (super.noSuchMethod(
        Invocation.getter(#signUp),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#signUp),
        ),
      ) as String);

  @override
  String get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
      ) as String);

  @override
  String get password => (super.noSuchMethod(
        Invocation.getter(#password),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#password),
        ),
      ) as String);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  String get phone => (super.noSuchMethod(
        Invocation.getter(#phone),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#phone),
        ),
      ) as String);

  @override
  String get location => (super.noSuchMethod(
        Invocation.getter(#location),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#location),
        ),
      ) as String);

  @override
  String get logout => (super.noSuchMethod(
        Invocation.getter(#logout),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#logout),
        ),
      ) as String);

  @override
  String get dashboard => (super.noSuchMethod(
        Invocation.getter(#dashboard),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#dashboard),
        ),
      ) as String);

  @override
  String get myDonations => (super.noSuchMethod(
        Invocation.getter(#myDonations),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#myDonations),
        ),
      ) as String);

  @override
  String get browseDonations => (super.noSuchMethod(
        Invocation.getter(#browseDonations),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#browseDonations),
        ),
      ) as String);

  @override
  String get myRequests => (super.noSuchMethod(
        Invocation.getter(#myRequests),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#myRequests),
        ),
      ) as String);

  @override
  String get incomingRequests => (super.noSuchMethod(
        Invocation.getter(#incomingRequests),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#incomingRequests),
        ),
      ) as String);

  @override
  String get messages => (super.noSuchMethod(
        Invocation.getter(#messages),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#messages),
        ),
      ) as String);

  @override
  String get profile => (super.noSuchMethod(
        Invocation.getter(#profile),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#profile),
        ),
      ) as String);

  @override
  String get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#settings),
        ),
      ) as String);

  @override
  String get createDonation => (super.noSuchMethod(
        Invocation.getter(#createDonation),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#createDonation),
        ),
      ) as String);

  @override
  String get title => (super.noSuchMethod(
        Invocation.getter(#title),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
      ) as String);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  String get category => (super.noSuchMethod(
        Invocation.getter(#category),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#category),
        ),
      ) as String);

  @override
  String get condition => (super.noSuchMethod(
        Invocation.getter(#condition),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#condition),
        ),
      ) as String);

  @override
  String get submit => (super.noSuchMethod(
        Invocation.getter(#submit),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#submit),
        ),
      ) as String);

  @override
  String get cancel => (super.noSuchMethod(
        Invocation.getter(#cancel),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#cancel),
        ),
      ) as String);

  @override
  String get approve => (super.noSuchMethod(
        Invocation.getter(#approve),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#approve),
        ),
      ) as String);

  @override
  String get decline => (super.noSuchMethod(
        Invocation.getter(#decline),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#decline),
        ),
      ) as String);

  @override
  String get request => (super.noSuchMethod(
        Invocation.getter(#request),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#request),
        ),
      ) as String);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  String get send => (super.noSuchMethod(
        Invocation.getter(#send),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#send),
        ),
      ) as String);

  @override
  String get search => (super.noSuchMethod(
        Invocation.getter(#search),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#search),
        ),
      ) as String);

  @override
  String get filter => (super.noSuchMethod(
        Invocation.getter(#filter),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#filter),
        ),
      ) as String);

  @override
  String get all => (super.noSuchMethod(
        Invocation.getter(#all),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#all),
        ),
      ) as String);

  @override
  String get food => (super.noSuchMethod(
        Invocation.getter(#food),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#food),
        ),
      ) as String);

  @override
  String get clothes => (super.noSuchMethod(
        Invocation.getter(#clothes),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#clothes),
        ),
      ) as String);

  @override
  String get books => (super.noSuchMethod(
        Invocation.getter(#books),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#books),
        ),
      ) as String);

  @override
  String get electronics => (super.noSuchMethod(
        Invocation.getter(#electronics),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#electronics),
        ),
      ) as String);

  @override
  String get furniture => (super.noSuchMethod(
        Invocation.getter(#furniture),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#furniture),
        ),
      ) as String);

  @override
  String get toys => (super.noSuchMethod(
        Invocation.getter(#toys),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#toys),
        ),
      ) as String);

  @override
  String get other => (super.noSuchMethod(
        Invocation.getter(#other),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#other),
        ),
      ) as String);

  @override
  String get pending => (super.noSuchMethod(
        Invocation.getter(#pending),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#pending),
        ),
      ) as String);

  @override
  String get approved => (super.noSuchMethod(
        Invocation.getter(#approved),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#approved),
        ),
      ) as String);

  @override
  String get declined => (super.noSuchMethod(
        Invocation.getter(#declined),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#declined),
        ),
      ) as String);

  @override
  String get completed => (super.noSuchMethod(
        Invocation.getter(#completed),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#completed),
        ),
      ) as String);

  @override
  String get cancelled => (super.noSuchMethod(
        Invocation.getter(#cancelled),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#cancelled),
        ),
      ) as String);

  @override
  String get donor => (super.noSuchMethod(
        Invocation.getter(#donor),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#donor),
        ),
      ) as String);

  @override
  String get receiver => (super.noSuchMethod(
        Invocation.getter(#receiver),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#receiver),
        ),
      ) as String);

  @override
  String get admin => (super.noSuchMethod(
        Invocation.getter(#admin),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#admin),
        ),
      ) as String);

  @override
  String get users => (super.noSuchMethod(
        Invocation.getter(#users),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#users),
        ),
      ) as String);

  @override
  String get donations => (super.noSuchMethod(
        Invocation.getter(#donations),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#donations),
        ),
      ) as String);

  @override
  String get donationCreated => (super.noSuchMethod(
        Invocation.getter(#donationCreated),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#donationCreated),
        ),
      ) as String);

  @override
  String get donationUpdated => (super.noSuchMethod(
        Invocation.getter(#donationUpdated),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#donationUpdated),
        ),
      ) as String);

  @override
  String get editDonation => (super.noSuchMethod(
        Invocation.getter(#editDonation),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#editDonation),
        ),
      ) as String);

  @override
  String get previous => (super.noSuchMethod(
        Invocation.getter(#previous),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#previous),
        ),
      ) as String);

  @override
  String get donationDetails => (super.noSuchMethod(
        Invocation.getter(#donationDetails),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#donationDetails),
        ),
      ) as String);

  @override
  String get basicInfoDescription => (super.noSuchMethod(
        Invocation.getter(#basicInfoDescription),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#basicInfoDescription),
        ),
      ) as String);

  @override
  String get donationTitle => (super.noSuchMethod(
        Invocation.getter(#donationTitle),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#donationTitle),
        ),
      ) as String);

  @override
  String get donationTitleHint => (super.noSuchMethod(
        Invocation.getter(#donationTitleHint),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#donationTitleHint),
        ),
      ) as String);

  @override
  String get requiredField => (super.noSuchMethod(
        Invocation.getter(#requiredField),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#requiredField),
        ),
      ) as String);

  @override
  String get titleTooShort => (super.noSuchMethod(
        Invocation.getter(#titleTooShort),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#titleTooShort),
        ),
      ) as String);

  @override
  String get donationDescription => (super.noSuchMethod(
        Invocation.getter(#donationDescription),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#donationDescription),
        ),
      ) as String);

  @override
  String get donationDescriptionHint => (super.noSuchMethod(
        Invocation.getter(#donationDescriptionHint),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#donationDescriptionHint),
        ),
      ) as String);

  @override
  String get descriptionTooShort => (super.noSuchMethod(
        Invocation.getter(#descriptionTooShort),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#descriptionTooShort),
        ),
      ) as String);

  @override
  String get donationLocation => (super.noSuchMethod(
        Invocation.getter(#donationLocation),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#donationLocation),
        ),
      ) as String);

  @override
  String get donationLocationHint => (super.noSuchMethod(
        Invocation.getter(#donationLocationHint),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#donationLocationHint),
        ),
      ) as String);

  @override
  String get locationTooShort => (super.noSuchMethod(
        Invocation.getter(#locationTooShort),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#locationTooShort),
        ),
      ) as String);

  @override
  String get quantity => (super.noSuchMethod(
        Invocation.getter(#quantity),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#quantity),
        ),
      ) as String);

  @override
  String get quantityHint => (super.noSuchMethod(
        Invocation.getter(#quantityHint),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#quantityHint),
        ),
      ) as String);

  @override
  String get invalidQuantity => (super.noSuchMethod(
        Invocation.getter(#invalidQuantity),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#invalidQuantity),
        ),
      ) as String);

  @override
  String get notes => (super.noSuchMethod(
        Invocation.getter(#notes),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#notes),
        ),
      ) as String);

  @override
  String get notesHint => (super.noSuchMethod(
        Invocation.getter(#notesHint),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#notesHint),
        ),
      ) as String);

  @override
  String get categoryAndCondition => (super.noSuchMethod(
        Invocation.getter(#categoryAndCondition),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#categoryAndCondition),
        ),
      ) as String);

  @override
  String get categoryDescription => (super.noSuchMethod(
        Invocation.getter(#categoryDescription),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#categoryDescription),
        ),
      ) as String);

  @override
  String get donationCategory => (super.noSuchMethod(
        Invocation.getter(#donationCategory),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#donationCategory),
        ),
      ) as String);

  @override
  String get requests => (super.noSuchMethod(
        Invocation.getter(#requests),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#requests),
        ),
      ) as String);

  @override
  String get analytics => (super.noSuchMethod(
        Invocation.getter(#analytics),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#analytics),
        ),
      ) as String);

  @override
  String get available => (super.noSuchMethod(
        Invocation.getter(#available),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#available),
        ),
      ) as String);

  @override
  String get unavailable => (super.noSuchMethod(
        Invocation.getter(#unavailable),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#unavailable),
        ),
      ) as String);

  @override
  String get delete => (super.noSuchMethod(
        Invocation.getter(#delete),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#delete),
        ),
      ) as String);

  @override
  String get edit => (super.noSuchMethod(
        Invocation.getter(#edit),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#edit),
        ),
      ) as String);

  @override
  String get save => (super.noSuchMethod(
        Invocation.getter(#save),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#save),
        ),
      ) as String);

  @override
  String get close => (super.noSuchMethod(
        Invocation.getter(#close),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#close),
        ),
      ) as String);

  @override
  String get yes => (super.noSuchMethod(
        Invocation.getter(#yes),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#yes),
        ),
      ) as String);

  @override
  String get no => (super.noSuchMethod(
        Invocation.getter(#no),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#no),
        ),
      ) as String);

  @override
  String get loading => (super.noSuchMethod(
        Invocation.getter(#loading),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#loading),
        ),
      ) as String);

  @override
  String get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#error),
        ),
      ) as String);

  @override
  String get success => (super.noSuchMethod(
        Invocation.getter(#success),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#success),
        ),
      ) as String);

  @override
  String get connectingHearts => (super.noSuchMethod(
        Invocation.getter(#connectingHearts),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#connectingHearts),
        ),
      ) as String);

  @override
  String get noDataAvailable => (super.noSuchMethod(
        Invocation.getter(#noDataAvailable),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#noDataAvailable),
        ),
      ) as String);

  @override
  String get donationImages => (super.noSuchMethod(
        Invocation.getter(#donationImages),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#donationImages),
        ),
      ) as String);

  @override
  String get imagesDescription => (super.noSuchMethod(
        Invocation.getter(#imagesDescription),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#imagesDescription),
        ),
      ) as String);

  @override
  String get addImages => (super.noSuchMethod(
        Invocation.getter(#addImages),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#addImages),
        ),
      ) as String);

  @override
  String get selectFromGallery => (super.noSuchMethod(
        Invocation.getter(#selectFromGallery),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#selectFromGallery),
        ),
      ) as String);

  @override
  String get takePhoto => (super.noSuchMethod(
        Invocation.getter(#takePhoto),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#takePhoto),
        ),
      ) as String);

  @override
  String get selectedImages => (super.noSuchMethod(
        Invocation.getter(#selectedImages),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#selectedImages),
        ),
      ) as String);

  @override
  String get reviewDonation => (super.noSuchMethod(
        Invocation.getter(#reviewDonation),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#reviewDonation),
        ),
      ) as String);

  @override
  String get reviewDescription => (super.noSuchMethod(
        Invocation.getter(#reviewDescription),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#reviewDescription),
        ),
      ) as String);

  @override
  String get images => (super.noSuchMethod(
        Invocation.getter(#images),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#images),
        ),
      ) as String);

  @override
  String get updateDonation => (super.noSuchMethod(
        Invocation.getter(#updateDonation),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#updateDonation),
        ),
      ) as String);

  @override
  String get markAllAsRead => (super.noSuchMethod(
        Invocation.getter(#markAllAsRead),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#markAllAsRead),
        ),
      ) as String);

  @override
  String get messageSettings => (super.noSuchMethod(
        Invocation.getter(#messageSettings),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#messageSettings),
        ),
      ) as String);

  @override
  String get archivedConversations => (super.noSuchMethod(
        Invocation.getter(#archivedConversations),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#archivedConversations),
        ),
      ) as String);

  @override
  String get blockedUsers => (super.noSuchMethod(
        Invocation.getter(#blockedUsers),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#blockedUsers),
        ),
      ) as String);

  @override
  String get searchMessages => (super.noSuchMethod(
        Invocation.getter(#searchMessages),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#searchMessages),
        ),
      ) as String);

  @override
  String get unread => (super.noSuchMethod(
        Invocation.getter(#unread),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#unread),
        ),
      ) as String);

  @override
  String get loadingMessages => (super.noSuchMethod(
        Invocation.getter(#loadingMessages),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#loadingMessages),
        ),
      ) as String);

  @override
  String get noMessages => (super.noSuchMethod(
        Invocation.getter(#noMessages),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#noMessages),
        ),
      ) as String);

  @override
  String get noMessagesDescription => (super.noSuchMethod(
        Invocation.getter(#noMessagesDescription),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#noMessagesDescription),
        ),
      ) as String);

  @override
  String get startConversation => (super.noSuchMethod(
        Invocation.getter(#startConversation),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#startConversation),
        ),
      ) as String);

  @override
  String get aboutDonation => (super.noSuchMethod(
        Invocation.getter(#aboutDonation),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#aboutDonation),
        ),
      ) as String);

  @override
  String get aboutRequest => (super.noSuchMethod(
        Invocation.getter(#aboutRequest),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#aboutRequest),
        ),
      ) as String);

  @override
  String get newConversationComingSoon => (super.noSuchMethod(
        Invocation.getter(#newConversationComingSoon),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#newConversationComingSoon),
        ),
      ) as String);

  @override
  String get messageSettingsComingSoon => (super.noSuchMethod(
        Invocation.getter(#messageSettingsComingSoon),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#messageSettingsComingSoon),
        ),
      ) as String);

  @override
  String get archivedConversationsComingSoon => (super.noSuchMethod(
        Invocation.getter(#archivedConversationsComingSoon),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#archivedConversationsComingSoon),
        ),
      ) as String);

  @override
  String get blockedUsersComingSoon => (super.noSuchMethod(
        Invocation.getter(#blockedUsersComingSoon),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#blockedUsersComingSoon),
        ),
      ) as String);

  @override
  String get next => (super.noSuchMethod(
        Invocation.getter(#next),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#next),
        ),
      ) as String);

  @override
  String get tryAgain => (super.noSuchMethod(
        Invocation.getter(#tryAgain),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#tryAgain),
        ),
      ) as String);
}
