// File generated by FlutterFire CLI.
// This file should be replaced with actual Firebase configuration
// Run: flutterfire configure --project=giving-bridge

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Get them from Firebase Console > Project Settings > General
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ9ACaziNQ6uwQBSiAvorKG8WqO8BRHsk',
    appId: '1:828798718567:web:162c926c3af58852bebac2',
    messagingSenderId: '828798718567',
    projectId: 'giving-bridge',
    authDomain: 'giving-bridge.firebaseapp.com',
    storageBucket: 'giving-bridge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ9ACaziNQ6uwQBSiAvorKG8WqO8BRHsk',
    appId: '1:828798718567:android:162c926c3af58852bebac2',
    messagingSenderId: '828798718567',
    projectId: 'giving-bridge',
    storageBucket: 'giving-bridge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ9ACaziNQ6uwQBSiAvorKG8WqO8BRHsk',
    appId: '1:828798718567:ios:162c926c3af58852bebac2',
    messagingSenderId: '828798718567',
    projectId: 'giving-bridge',
    storageBucket: 'giving-bridge.appspot.com',
    iosBundleId: 'com.givingbridge.app',
  );
}
